### ISSUE TITLE
Please fix the unstable test

### ISSUE THREAD

**Issue by tastvatsatryan-vineti** [artyomabrahamyan/tdd_exercise_vineti#1]
## Counter.test.js

```
    test("the value should be randomized(changed) whenever clicking on randomize button", () => {
        const {value} = counter.state();
        const randButton = counter.findWhere(b => b.type() === 'button' && b.text() === 'Randomize')
        randButton.simulate('click');
        expect(counter.find('span').text()).not.toBe(`${value}`);
    });
```

This test is unstable and there is a possibility that it will produce a false negative error.

Please fix.

**Comment by artyomabrahamyan** [comment]
Thanks.

The test meant to compare that the randomly generated value does not equal to the current value(expected behavior by the user). So made the change in the component to make sure it is working properly.

**Comment by tastvatsatryan-vineti** [comment]
I think there is a chance when randomly generated number is equal to the current value. In this case the test will fail, even though the functionality is correct (false negative).

That's why tests should be deterministic, they shouldn't dependent on how many times you run it and in which sequence.

Can we somehow mock random number generator function in the test so we are sure it returns the  same number every time we run it?

**Comment by artyomabrahamyan** [comment]
Yes, I got it. Please take a look on what I have added to the Counter component's randomize function in order to always produce same results. 

IMHO, the generated value should not equal to the current one & will always be deterministic.

Please let me know if thats OK.

**Comment by tastvatsatryan-vineti** [comment]
This won't work.

Now we are changing the functional code to make our test valid/stable. Moreover, we are breaking the acceptance criteria by excluding same number case (which means the generator isn't random anymore).

I am looking for a solution in tests without breaking randomness and violating the acceptance criteria.

**Comment by artyomabrahamyan** [comment]
So basically if do not want to excludr same number then I wilk revert the change and will leave the new test with mocking random number. It should be okay I guess.

**Comment by artyomabrahamyan** [comment]
Thanks for mentioning, because I thought that repetition case should be excluded and it was my fault to miss that part in component.

**Comment by tastvatsatryan-vineti** [comment]
I see you have updated the functionality

```
  onRandomize(id) {
    const values = this.state.values.slice(); 
    let randomNum  = this.generateRandom();
    values[id] = randomNum;
    this.setState({values});      
  }

  generateRandom() {
      return Math.floor(Math.random() * 1001);
  }
```

```
    test("when clicking on randomize button the random number should be generated", async () => {
      const mockGenerateRandom = jest.fn();
      mockGenerateRandom.mockReturnValue(25);
      app.instance().generateRandom  = mockGenerateRandom;
      const counter = app.find(Counter).dive();
      counter.findWhere(b => b.type() === 'button' && b.text() ==='Randomize').simulate('click');
      expect(app.state().values[0]).toBe(25);
    });
```

This makes sense to me, closing the issue.
