### ISSUE TITLE
Not understandable test

### ISSUE THREAD

**Issue by nghevandiani-vineti** [artyomabrahamyan/tdd_exercise_vineti#3]
Could you please explain/fix the test below?

```
    setTimeout(() => {      
      app.update();
        expect(app.find('span')).toHaveLength(1);
        const addButton = app.findWhere((e) => e.type() === 'button' && e.text() === 'Add Counter');
        addButton.simulate('click');
        setTimeout(() => {
          app.update();
          expect(app.find('span')).toHaveLength(2)              
          }, 100)
        }, 100)      
});
```

**Comment by artyomabrahamyan** [comment]
Sure, when App component mounted we expect to have only one counter then after clicking the add button we expect to have two.

**Comment by nghevandiani-vineti** [comment]
Yes, agree. The problem are the setTimeout-s. Why are they used?

**Comment by artyomabrahamyan** [comment]
Yes, I got it, so the call from componentDidMount was asynchronous and it was intended to be kind of awaited. Nonetheless I have made the changes to imrpove readability and avoid thos setTimeouts. 

Thx for letting me know.

**Comment by artyomabrahamyan** [comment]
@nghevandiani-vineti the issue was fixed.
