### ISSUE TITLE
Old counters lose value when adding new one

### ISSUE THREAD

**Issue by nghevandiani-vineti** [artyomabrahamyan/tdd_exercise_vineti#4]
The old counters lose their values when clicking on `add counter` button.

To reprod:
- Change value of initial counter
- Add new counter

Expected:
The old counter should keep value.

Actual:
The old counter resets to the value came from request.

**Comment by artyomabrahamyan** [comment]
Thanks for noticing and your time Narek jan.

**Comment by artyomabrahamyan** [comment]
@nghevandiani-vineti the issue was fixed.
